
# Avvertenza {-}

\large

Questo lavoro è un work in progress, questa non è la versione definitiva, sconsiglio di stampare tutto. 

\normalsize


Appunti di Statistica © 2023 di Patrizio Frederic è distribuito
sotto licenza CC BY-NC-ND 4.0
https://creativecommons.org/licenses/by-nc-nd/4.0/

You are free to:
Share — copy and redistribute the material in any medium or format
The licensor cannot revoke these freedoms as long as you follow the license terms.
Under the following terms:
Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

NonCommercial — You may not use the material for commercial purposes.

NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.

No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.




# Introduzione {-}

Durante il lock down della prima ondata, nel marzo del 2020, ho iniziato a trascrivere
i miei appunti, raccolti negli ultimi 17 anni, in diapositive. Questa è una rielaborazione
di quelle diapositive a cui è stato aggiunto parte dell'eserciziario realizzato con Michele Lalla. 
L'esposizione degli argomenti ricalca il corso di Statistica che con Michele Lalla abbiamo 
progettato per i corsi di CLEF e CLEA nel periodo che va dal 2008 al 2019, al quale ho 
portato alcune modifiche di forma e qualche aggiunta.

Questo manoscritto è diviso in tre parti, la prima dedicata alla statistica descrittiva nella quale 
vengono date le nozioni di base di descrizione di una popolazione, le sue rappresentazioni grafiche,
la media e la variabilità. Nella seconda parte verranno date le nozioni di base di teoria e calcolo delle probabilità.
Dal concetto di evento fino alle principali variabili casuali, il teorema del limite centrale e la distribuzione
delle principali statistiche campionarie. Nella terza e ultima parte verranno sviluppati 
i principi di base di inferenza classica, dalla stima puntuale alla stima intervallare, la teoria dei test, 
il modello di regressione lineare e il test del chi-quadro.

Questo materiale, che non è ancora un libro, è da considerarsi il canovaccio d'appunti sul quale 
costruisco le mie lezioni.  Non è da ritenersi alternativo alle lezioni in aula o ad un libro di testo. 
È ancora incompleto e disseminato di errori e imprecisioni.

Un ringraziamento speciale va alle mie donne e a Michele Lalla, amico, collega e maestro.

Bologna, il `r format(Sys.Date(),"%d-%m-%Y")`.
